### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by nickfan** [atom-compare-files/atom-compare-files#43]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2
### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/user/.atom/packages/compare-files/lib/compare-files.js:81

TypeError: atom.workspace.open(...).done is not a function
    at atom-workspace.compare (/Users/user/.atom/packages/compare-files/lib/compare-files.js:81:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:08.0 compare-files:compare (span.name.icon.icon-file-text)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-design-syntax"
    ],
    "disabledPackages": [
      "open-terminal-here",
      "open-terminal-here",
      "log-console",
      "remote-edit",
      "atom-ctags",
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.0
autocomplete-ctags, v0.3.3
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
browser-plus, v0.0.54
build, v0.51.0
compare-files, v0.6.2
daylerees, vundefined
docblockr, v0.7.3
emmet, v2.3.17
emmet-snippets-compatibility, v1.0.1
file-icons, v1.6.13
javascript-snippets, v1.0.0
language-blade, v0.16.0
language-vue, v0.8.0
laravel, v0.7.0
material-design-syntax, v1.7.0
minimap, v4.18.2
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.4.0
minimap-pigments, v0.1.7
open-recent, v4.0.1
pigments, v0.19.3
pretty-json, v0.4.1
project-manager, v2.6.5
project-view, v0.4.1
recent-files-fuzzy-finder, v0.2.4
recent-projects, v0.9.5
remote-sync, v3.5.0
symbol-gen, v1.0.0
sync-settings, v0.6.0
terminal-status, v1.6.8
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by PointedEars** [comment]
Still there in

*Atom Version:* 1.4.2
*System:* Mac OS X 10.11.3

**Comment by ParitoshBh** [comment]
Commit cbd07bb81ed26ad272f5a9548f82fc7ed60a89d8 should take care of this since .done() isn't being used anymore. Closing this issue for the time being. Reopen if you still face same issue.
