### ISSUE TITLE
Can't open files with a "%" in the filename

### ISSUE THREAD

**Issue by vlvrd** [atom-compare-files/atom-compare-files#46]
When I try to open a file that contains a "%" (foo_%.bb) in it's filename, the package won't allow Atom to open it.

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2
### Stack Trace

Uncaught URIError: URI malformed

```
At /home/sergio/.atom/packages/compare-files/lib/compare-files.js:51

URIError: URI malformed
    at decodeURI (native)
    at /home/sergio/.atom/packages/compare-files/lib/compare-files.js:51:18
    at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:489:22)
    at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:424:19)
    at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:476:28)
    at tree-view-file.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:188:26)
    at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-detect-indentation, v1.1.0
autocomplete-clang, v0.9.4
autocomplete-python, v1.8.2
compare-files, v0.6.2
highlight-selected, v0.11.2
linter, v1.11.14
linter-clang, v3.4.4
linter-flake8, v1.13.2
minimap, v4.24.7
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
monokai, v0.18.0
open-recent, v5.0.0
rst-preview, v1.3.1

# Dev
No dev packages
```

**Comment by ParitoshBh** [comment]
Commit a3aa79272ee47429283fa944efdda7bb6fd499f7 takes care of this. It's a dirty hack but it works. I am closing this issue for now. If you encounter the same issue again, please reopen this!
